### ISSUE TITLE
asking for transfering the npm package name

### ISSUE THREAD

**Issue by DennisJames** [tristanls/anodejs#3]
Hi, tristanls.
I'm dennis from China. I am trying to publish an npm package named also 'anode'. I see that your "anode" seems not use anymore. So, could you give it to me ? Thank you very much.

**Comment by tristanls** [comment]
I reached out to `npm` to unpublish all existing content prior to transferring. Awaiting their response.

**Comment by tristanls** [comment]
With the help of `npm` support I've unpublished the `anode` package. Its name will be blocked from reuse for 24 hours and all past versions will have been consumed and also blocked from reuse.

You should be able to claim it after 24 hours.

**Comment by DennisJames** [comment]
Thank you very much!
